package org.unlaxer.tinyexpression.p4;

import java.util.Locale;
import java.util.Optional;
import java.util.function.Supplier;

/**
 * Which parser implementation sits behind {@link P4PreferredAstMapper}.
 *
 * <ul>
 *   <li>{@link #UBNFC} (default since 2.0.0): the dependency-free parser generated by ubnfc from
 *       the same P4 grammar, vendored under {@code org.unlaxer.tinyexpression.p4.ubnfc.generated}
 *       (pin: {@code src/main/java/org/unlaxer/tinyexpression/p4/ubnfc/UBNFC_PIN}).</li>
 *   <li>{@link #LEGACY}: the pre-2.0 unlaxer combinator path ({@code TinyExpressionP4Parsers} +
 *       {@code TinyExpressionP4Mapper}). Retained through 2.x as an escape hatch; scheduled for
 *       removal in 3.0.</li>
 * </ul>
 *
 * <p>Resolution order, most specific first:
 * <ol>
 *   <li>a scoped override: {@link #with(P4ParserEngine, Supplier)}, which is what
 *       {@code CalculatorCreatorRegistry.forBackend(backend, engine)} and a FormulaInfo block's
 *       {@code p4Engine:} field use;</li>
 *   <li>the system property {@value #SYSTEM_PROPERTY} ({@code ubnfc} or {@code legacy});</li>
 *   <li>{@link #DEFAULT} = {@link #UBNFC}.</li>
 * </ol>
 * An unrecognised value in either place is an error, never a silent fallback.
 */
public enum P4ParserEngine {
  UBNFC("ubnfc"),
  LEGACY("legacy");

  /** JVM-wide switch, e.g. {@code -Dtinyexpression.p4.engine=legacy}. */
  public static final String SYSTEM_PROPERTY = "tinyexpression.p4.engine";

  /** FormulaInfo block field selecting the engine for that block, e.g. {@code p4Engine:legacy}. */
  public static final String FORMULA_INFO_KEY = "p4Engine";

  /** Calculator marker holding the engine that built the calculator. */
  public static final String CALCULATOR_MARKER = "_tinyP4ParserEngine";

  public static final P4ParserEngine DEFAULT = UBNFC;

  private static final ThreadLocal<P4ParserEngine> SCOPED = new ThreadLocal<>();

  private final String id;

  P4ParserEngine(String id) {
    this.id = id;
  }

  /** Lower-case identifier used by the system property and the FormulaInfo field. */
  public String id() {
    return id;
  }

  /** Case-insensitive parse of {@code ubnfc} / {@code legacy}; empty for blank or unknown. */
  public static Optional<P4ParserEngine> parse(String value) {
    if (value == null || value.isBlank()) {
      return Optional.empty();
    }
    String normalized = value.strip().toLowerCase(Locale.ROOT);
    for (P4ParserEngine engine : values()) {
      if (engine.id.equals(normalized)) {
        return Optional.of(engine);
      }
    }
    return Optional.empty();
  }

  /** Like {@link #parse(String)} but rejects unknown non-blank values. */
  public static Optional<P4ParserEngine> parseStrict(String value, String origin) {
    Optional<P4ParserEngine> parsed = parse(value);
    if (parsed.isEmpty() && value != null && !value.isBlank()) {
      throw new IllegalArgumentException("unknown P4 parser engine in " + origin + ": '" + value
          + "' (expected 'ubnfc' or 'legacy')");
    }
    return parsed;
  }

  /** The engine in effect for the current thread (scoped override, then property, then default). */
  public static P4ParserEngine current() {
    P4ParserEngine scoped = SCOPED.get();
    if (scoped != null) {
      return scoped;
    }
    return configured();
  }

  /** The JVM-wide engine: the system property, else {@link #DEFAULT}. Ignores scoped overrides. */
  public static P4ParserEngine configured() {
    return parseStrict(System.getProperty(SYSTEM_PROPERTY), "-D" + SYSTEM_PROPERTY).orElse(DEFAULT);
  }

  /**
   * Runs {@code action} with {@code engine} in effect on this thread. {@code null} means
   * "no override" (the property / default applies). Nested calls restore the outer value.
   */
  public static <T> T with(P4ParserEngine engine, Supplier<T> action) {
    if (engine == null) {
      return action.get();
    }
    P4ParserEngine previous = SCOPED.get();
    SCOPED.set(engine);
    try {
      return action.get();
    } finally {
      if (previous == null) {
        SCOPED.remove();
      } else {
        SCOPED.set(previous);
      }
    }
  }

  public static void with(P4ParserEngine engine, Runnable action) {
    with(engine, () -> {
      action.run();
      return null;
    });
  }
}
