#!/usr/bin/env python3
"""Regenerate src/generated/compat.rs, the ubnfc-AST -> public-AST adapter.

Both `src/generated/ast.rs` (this crate's published AST) and
`src/generated/ubnfc/ast.rs` (the vendored ubnfc AST) are derived from the same P4
Grammar IR, so they have the same 86 node names and the same field names. This script
reads both and emits the conversion, failing loudly if a node, a field or a field type
pairing it does not know about appears -- that is the signal that the grammar changed and
`ast.rs` needs updating too.

Usage: python3 rust/scripts/generate-compat.py [--check]
"""

import re
import sys
from pathlib import Path

RUST = Path(__file__).resolve().parent.parent
UBNFC_AST = RUST / "tinyexpression-rs/src/generated/ubnfc/ast.rs"
PUBLIC_AST = RUST / "tinyexpression-rs/src/generated/ast.rs"
OUTPUT = RUST / "tinyexpression-rs/src/generated/compat.rs"

PREFIX = "g_TinyExpressionP4AST_2e_"

HEADER = '''// Adapter from the vendored ubnfc typed AST to this crate's published `Ast`.
//
// Generated by `rust/scripts/generate-compat.py`; do not edit by hand. Both trees come from
// the same P4 Grammar IR, so they carry the same 86 node names and the same field names.
// Exactly one shape difference is reconciled here: ubnfc keeps the innermost operand of an
// operator chain wrapped in a `BinaryExpr` whose only content is that operand's text, while
// this crate's published AST puts the text straight into the operand slot
// (`AstValue::Text`). `Converter::value` folds that wrapper away, which is what keeps the
// published JSON shape identical to the one the previous parser produced
// (see `README.md`, "AST shape").

use super::ast::{Ast, AstValue};
use super::ubnfc::ast::Ast as U;
use crate::Span;

/// Converts one ubnfc AST into the published `Ast`.
///
/// `clip` bounds every span, which the frontend needs when it re-parses a masked copy of the
/// source from a non-root entry rule: the entry rule may match trailing trivia that lies
/// outside the expression the document actually owns.
pub struct Converter {
    clip: Option<Span>,
}

/// Converts `source` without bounding spans.
pub fn convert(source: &U) -> Result<Ast, String> {
    Converter::new(None).node_value(source)
}

/// Converts `source`, clamping every span into `clip`.
pub fn convert_clipped(source: &U, clip: Option<Span>) -> Result<Ast, String> {
    Converter::new(clip).node_value(source)
}

impl Converter {
    pub fn new(clip: Option<Span>) -> Self {
        Self { clip }
    }

    fn span(&self, value: [usize; 2]) -> Span {
        let span = Span { start: value[0], end: value[1] };
        match self.clip {
            None => span,
            Some(bounds) => {
                let start = span.start.clamp(bounds.start, bounds.end);
                Span { start, end: span.end.clamp(start, bounds.end) }
            }
        }
    }

    fn node(&self, value: &U) -> Result<Box<Ast>, String> {
        Ok(Box::new(self.node_value(value)?))
    }

    fn opt_node(&self, value: &Option<Box<U>>) -> Result<Option<Box<Ast>>, String> {
        value.as_deref().map(|inner| self.node(inner)).transpose()
    }

    fn list(&self, values: &[U]) -> Result<Vec<Ast>, String> {
        values.iter().map(|value| self.node_value(value)).collect()
    }

    /// Folds ubnfc's innermost-operand wrapper into the published `AstValue::Text`.
    ///
    /// `owner` is the span of the node that holds this slot; a bare text capture carries no
    /// span of its own in the ubnfc AST, so the owner's span stands in for it.
    fn value(&self, source: &U, owner: [usize; 2]) -> Result<AstValue, String> {
        match source {
            U::Text(text) => {
                return Ok(AstValue::Text {
                    text: text.clone(),
                    span: self.span(owner),
                })
            }
            U::{prefix}BinaryExpr(inner)
                if inner.g_left.is_none() && inner.g_right.is_empty() && inner.g_op.len() == 1 =>
            {
                return Ok(AstValue::Text {
                    text: inner.g_op[0].clone(),
                    span: self.span(inner.span),
                })
            }
            _ => {}
        }
        Ok(AstValue::Node(Box::new(self.node_value(source)?)))
    }

    fn required_value(
        &self,
        source: &Option<Box<U>>,
        name: &str,
        owner: [usize; 2],
    ) -> Result<AstValue, String> {
        match source {
            Some(inner) => self.value(inner, owner),
            None => Err(format!("expected exactly one value for {name}, got 0")),
        }
    }

    fn value_list(&self, values: &[U], owner: [usize; 2]) -> Result<Vec<AstValue>, String> {
        values.iter().map(|value| self.value(value, owner)).collect()
    }

    #[allow(clippy::too_many_lines)]
    pub fn node_value(&self, source: &U) -> Result<Ast, String> {
        Ok(match source {
            U::Text(text) => {
                return Err(format!("unexpected bare text {text:?} where a node was required"))
            }
            U::Null => return Err("unexpected null where a node was required".to_owned()),
'''

FOOTER = """        })
    }
}
"""

CONVERSIONS = {
    ("String", "String"): "source.g_{f}.clone()",
    ("Option<String>", "Option<String>"): "source.g_{f}.clone()",
    ("Vec<String>", "Vec<String>"): "source.g_{f}.clone()",
    ("Box<Ast>", "Box<Ast>"): "self.node(&source.g_{f})?",
    ("Option<Box<Ast>>", "Option<Box<Ast>>"): "self.opt_node(&source.g_{f})?",
    ("Vec<Ast>", "Vec<Ast>"): "self.list(&source.g_{f})?",
    ("Box<Ast>", "AstValue"): "self.value(&source.g_{f}, source.span)?",
    ("Option<Box<Ast>>", "AstValue"): 'self.required_value(&source.g_{f}, "{f}", source.span)?',
    ("Vec<Ast>", "Vec<AstValue>"): "self.value_list(&source.g_{f}, source.span)?",
}


def ubnfc_nodes() -> "dict[str, list[tuple[str, str]]]":
    text = UBNFC_AST.read_text(encoding="utf-8")
    pattern = (
        r"pub struct " + PREFIX + r"(\w+) \{ pub span:Span, pub node_id:usize,\n"
        r"((?:pub g_\w+: [^\n]+\n)*)\}"
    )
    nodes = {}
    for match in re.finditer(pattern, text):
        fields = [
            (field.group(1), field.group(2).rstrip(","))
            for field in re.finditer(r"pub g_(\w+): ([^\n]+)\n", match.group(2))
        ]
        nodes[match.group(1)] = fields
    return nodes


def split_fields(rest: str) -> "list[str]":
    fields, depth, current = [], 0, ""
    for character in rest:
        if character in "<([":
            depth += 1
        if character in ">)]":
            depth -= 1
        if character == "," and depth == 0:
            fields.append(current.strip())
            current = ""
        else:
            current += character
    if current.strip():
        fields.append(current.strip())
    return fields


def public_nodes() -> "dict[str, list[tuple[str, str]]]":
    text = PUBLIC_AST.read_text(encoding="utf-8")
    body = re.search(r"pub enum Ast \{\n(.*?)\n\}\n", text, re.S).group(1)
    nodes = {}
    for line in body.split("\n"):
        line = line.strip().rstrip(",")
        if not line:
            continue
        match = re.match(r"r#(\w+) \{ span: Span(.*)\}$", line)
        if not match:
            sys.exit(f"cannot read variant: {line}")
        rest = match.group(2).strip().lstrip(",").strip()
        fields = []
        for field in split_fields(rest):
            name, kind = field.split(":", 1)
            fields.append((re.sub(r"^r#", "", name.strip()), kind.strip()))
        nodes[match.group(1)] = fields
    return nodes


def render() -> str:
    ubnfc, public = ubnfc_nodes(), public_nodes()
    if set(ubnfc) != set(public):
        sys.exit(
            "node sets differ; regenerate the vendored parser and update ast.rs\n"
            f"  only in ubnfc:  {sorted(set(ubnfc) - set(public))}\n"
            f"  only in public: {sorted(set(public) - set(ubnfc))}"
        )
    out = [HEADER.replace("{prefix}", PREFIX)]
    for name, fields in ubnfc.items():
        expected = public[name]
        if [field for field, _ in fields] != [field for field, _ in expected]:
            sys.exit(f"{name}: field names differ: {fields} vs {expected}")
        out.append(f"            U::{PREFIX}{name}(source) => Ast::r#{name} {{\n")
        out.append("                span: self.span(source.span),\n")
        for (field, ubnfc_type), (_, public_type) in zip(fields, expected):
            template = CONVERSIONS.get((ubnfc_type, public_type))
            if template is None:
                sys.exit(f"{name}.{field}: no rule for {ubnfc_type} -> {public_type}")
            out.append(f"                r#{field}: {template.format(f=field)},\n")
        out.append("            },\n")
    out.append(FOOTER)
    return "".join(out)


def main() -> None:
    rendered = render()
    if "--check" in sys.argv[1:]:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != rendered:
            sys.exit(f"{OUTPUT} is stale; run python3 rust/scripts/generate-compat.py")
        print("compat.rs: up to date")
        return
    OUTPUT.write_text(rendered, encoding="utf-8")
    print(f"compat.rs: {len(rendered.splitlines())} lines")


if __name__ == "__main__":
    main()
