package org.unlaxer.tinyexpression.p4.ubnfc;

import java.io.IOException;
import java.io.InputStream;
import java.io.UncheckedIOException;
import java.lang.reflect.RecordComponent;
import java.net.URISyntaxException;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.function.Supplier;

import org.unlaxer.tinyexpression.generated.p4.TinyExpressionP4AST;
import org.unlaxer.tinyexpression.p4.P4ParserEngine;
import org.unlaxer.tinyexpression.p4.P4PreferredAstMapper;
import org.unlaxer.tinyexpression.p4.ubnfc.generated.api.Json;
import org.unlaxer.tinyexpression.parser.ExpressionType;
import org.unlaxer.tinyexpression.parser.ExpressionTypes;

/**
 * Runs the same input through {@link P4PreferredAstMapper} under {@link P4ParserEngine#CLASSIC}
 * and {@link P4ParserEngine#UBNFC} in one JVM and compares canonical JSON, selectionMode and
 * failures. Differences are recorded, never dropped.
 */
final class EngineComparison {

  static final String CORPUS = "/p4/ubnfc-parity/te-formulas.json";
  static final String FIXTURES = "/p4/ubnfc-parity/fixtures";
  static final String TIMEOUT_PROPERTY = "tinyexpression.p4.parse.timeout.millis";

  record Case(String source, String origin, ExpressionType preferredType,
      String preferredAstSimpleName, boolean negative) {

    boolean nonBmp() {
      return source.codePoints().anyMatch(c -> c > 0xFFFF);
    }
  }

  record Outcome(String selectionMode, String json, String failure) {
    static Outcome ok(P4PreferredAstMapper.ParsedAst parsed) {
      return new Outcome(parsed.selectionMode(), CanonicalAst.json(parsed), null);
    }

    static Outcome failed(Throwable failure) {
      return new Outcome(null, null, failure.getClass().getName() + ": " + failure.getMessage());
    }

    boolean accepted() {
      return failure == null;
    }

    boolean deadline() {
      return failure != null
          && failure.startsWith(P4PreferredAstMapper.ParseDeadlineExceededException.class.getName());
    }
  }

  record Row(Case testCase, Outcome classic, Outcome ubnfc, String verdict) {
    boolean agrees() {
      return verdict.equals("same") || verdict.equals("both-reject")
          || verdict.equals(PUBLISHED_MAPPER_VERDICT);
    }
  }

  /**
   * True when the AST was generated by the <b>published</b> unlaxer-dsl 3.0.15 (what Java CI and
   * the 2.0.0 release build against), recognised by its {@code SliceExpr.start} being a String.
   * The development generator (unlaxer-parser source pin, and a locally installed newer build)
   * declares it {@code Optional<Object>}.
   */
  static final boolean PUBLISHED_3_0_15_MAPPER = detectPublishedMapper();

  /**
   * Verdict for an AST difference fully explained by the two known mapper bugs of the published
   * unlaxer-dsl 3.0.15 generator, which the classic engine inherits and ubnfc does not have
   * (ubnfc returns what the fixed generator returns):
   * <ol>
   *   <li>{@code import X as alias}: published puts the alias into {@code method} and leaves
   *       {@code alias} empty ({@code method="alias", alias=""} instead of {@code method=null,
   *       alias="alias"}).</li>
   *   <li>{@code receiver.contains/startsWith/endsWith(p...)} ({@code *DotExpr}): published repeats
   *       the receiver as an extra first element of {@code patterns}.</li>
   * </ol>
   * Only ever produced when {@link #PUBLISHED_3_0_15_MAPPER}; any other difference stays a failure.
   */
  static final String PUBLISHED_MAPPER_VERDICT = "same-modulo-published-3.0.15-mapper-bugs";

  private static final Set<String> DOT_PATTERN_TYPES =
      Set.of("ContainsDotExpr", "StartsWithDotExpr", "EndsWithDotExpr");

  private EngineComparison() {}

  private static boolean detectPublishedMapper() {
    for (RecordComponent component : TinyExpressionP4AST.SliceExpr.class.getRecordComponents()) {
      if (component.getName().equals("start")) {
        return component.getType() == String.class;
      }
    }
    return false;
  }

  /** Structural equality of canonical JSON trees, allowing only the published-mapper bugs. */
  @SuppressWarnings("unchecked")
  static boolean explainedByPublishedMapper(Object classic, Object ubnfc) {
    if (Objects.equals(classic, ubnfc)) {
      return true;
    }
    if (classic instanceof List<?> left && ubnfc instanceof List<?> right) {
      if (left.size() != right.size()) {
        return false;
      }
      for (int i = 0; i < left.size(); i++) {
        if (!explainedByPublishedMapper(left.get(i), right.get(i))) {
          return false;
        }
      }
      return true;
    }
    if (!(classic instanceof Map<?, ?> left) || !(ubnfc instanceof Map<?, ?> right)) {
      return false;
    }
    if (!Objects.equals(left.get("type"), right.get("type"))
        || !Objects.equals(left.get("span"), right.get("span"))) {
      return false;
    }
    if (!(left.get("fields") instanceof Map<?, ?> leftFieldsRaw)
        || !(right.get("fields") instanceof Map<?, ?> rightFieldsRaw)) {
      return Objects.equals(left, right);
    }
    var leftFields = new LinkedHashMap<>((Map<String, Object>) leftFieldsRaw);
    var rightFields = new LinkedHashMap<>((Map<String, Object>) rightFieldsRaw);
    String type = String.valueOf(left.get("type"));
    if (type.equals("ImportDeclarationExpr")
        && Objects.equals(leftFields.get("alias"), "")
        && rightFields.get("method") == null
        && leftFields.get("method") != null
        && Objects.equals(leftFields.get("method"), rightFields.get("alias"))) {
      leftFields.remove("method");
      leftFields.remove("alias");
      rightFields.remove("method");
      rightFields.remove("alias");
    }
    if (DOT_PATTERN_TYPES.contains(type)
        && leftFields.get("patterns") instanceof List<?> leftPatterns
        && rightFields.get("patterns") instanceof List<?> rightPatterns
        && leftPatterns.size() == rightPatterns.size() + 1) {
      leftFields.put("patterns", new ArrayList<>(leftPatterns.subList(1, leftPatterns.size())));
    }
    if (!leftFields.keySet().equals(rightFields.keySet())) {
      return false;
    }
    for (String key : leftFields.keySet()) {
      if (!explainedByPublishedMapper(leftFields.get(key), rightFields.get(key))) {
        return false;
      }
    }
    return true;
  }

  /** 324 formulas the test suite feeds the facade + the 16 ubnfc p4-java fixtures. */
  static List<Case> corpus() throws IOException {
    var cases = new ArrayList<Case>();
    try (InputStream in = EngineComparison.class.getResourceAsStream(CORPUS)) {
      String text = new String(in.readAllBytes(), StandardCharsets.UTF_8);
      for (Object entry : Json.array(Json.read(text))) {
        Map<String, Object> value = Json.object(entry);
        cases.add(new Case(
            (String) value.get("source"),
            (String) value.get("origin"),
            expressionType((String) value.get("preferredType")),
            (String) value.get("preferredAstSimpleName"),
            Boolean.TRUE.equals(value.get("negative"))));
      }
    }
    for (Path file : fixtureFiles()) {
      String name = file.getFileName().toString();
      cases.add(new Case(Files.readString(file), "ubnfc p4-java fixture " + name, null, null,
          name.startsWith("invalid") || name.startsWith("complex-half")
              || name.startsWith("complex-tail")));
    }
    return cases;
  }

  static List<Path> fixtureFiles() {
    URL url = EngineComparison.class.getResource(FIXTURES);
    if (url == null) {
      throw new IllegalStateException("missing test resource " + FIXTURES);
    }
    try (var stream = Files.list(Path.of(url.toURI()))) {
      return stream.filter(path -> path.getFileName().toString().endsWith(".tiny")).sorted().toList();
    } catch (IOException e) {
      throw new UncheckedIOException(e);
    } catch (URISyntaxException e) {
      throw new IllegalStateException(e);
    }
  }

  private static ExpressionType expressionType(String name) {
    return name == null || name.isBlank() ? null : ExpressionTypes.valueOf(name);
  }

  static Row compare(Case testCase) {
    Outcome classic = run(testCase, P4ParserEngine.CLASSIC);
    Outcome ubnfc = run(testCase, P4ParserEngine.UBNFC);
    return new Row(testCase, classic, ubnfc, verdict(classic, ubnfc));
  }

  static String verdict(Outcome classic, Outcome ubnfc) {
    if (!classic.accepted() || !ubnfc.accepted()) {
      if (!classic.accepted() && !ubnfc.accepted()) {
        return classic.failure().equals(ubnfc.failure()) ? "both-reject" : "reject-message-differs";
      }
      return classic.accepted() ? "ubnfc-only-reject" : "classic-only-reject";
    }
    if (!classic.selectionMode().equals(ubnfc.selectionMode())) {
      return "mode-differs";
    }
    if (classic.json().equals(ubnfc.json())) {
      return "same";
    }
    if (PUBLISHED_3_0_15_MAPPER
        && explainedByPublishedMapper(Json.read(classic.json()), Json.read(ubnfc.json()))) {
      return PUBLISHED_MAPPER_VERDICT;
    }
    return "ast-differs";
  }

  static Outcome run(Case testCase, P4ParserEngine engine) {
    return P4ParserEngine.with(engine, (Supplier<Outcome>) () -> {
      try {
        if (testCase.preferredAstSimpleName() != null) {
          return Outcome.ok(P4PreferredAstMapper.parseByAstSimpleNameDetailed(
              testCase.source(), testCase.preferredAstSimpleName(), 0L));
        }
        return Outcome.ok(P4PreferredAstMapper.parseDetailed(
            testCase.source(), testCase.preferredType()));
      } catch (RuntimeException | StackOverflowError failure) {
        return Outcome.failed(failure);
      }
    });
  }

  /** Runs {@code action} with the default parse deadline set to {@code millis} (0 = none). */
  static <T> T withParseTimeout(long millis, Supplier<T> action) {
    String previous = System.setProperty(TIMEOUT_PROPERTY, Long.toString(millis));
    try {
      return action.get();
    } finally {
      if (previous == null) {
        System.clearProperty(TIMEOUT_PROPERTY);
      } else {
        System.setProperty(TIMEOUT_PROPERTY, previous);
      }
    }
  }

  static void writeReport(List<Row> rows, Path out) {
    try {
      Files.createDirectories(out.getParent());
      var text = new StringBuilder("verdict\torigin\tclassic\tubnfc\tsource\n");
      for (Row row : rows) {
        text.append(row.verdict()).append('\t')
            .append(row.testCase().origin()).append('\t')
            .append(escape(describe(row.classic()))).append('\t')
            .append(escape(describe(row.ubnfc()))).append('\t')
            .append(escape(row.testCase().source())).append('\n');
      }
      Files.writeString(out, text.toString());
    } catch (IOException e) {
      throw new UncheckedIOException(e);
    }
  }

  private static String describe(Outcome outcome) {
    return outcome.accepted() ? outcome.selectionMode() : outcome.failure();
  }

  private static String escape(String value) {
    return value == null ? "" : value.replace("\\", "\\\\").replace("\n", "\\n").replace("\t", "\\t");
  }

  static Map<String, Integer> tally(List<Row> rows) {
    var counts = new LinkedHashMap<String, Integer>();
    for (Row row : rows) {
      counts.merge(row.verdict(), 1, Integer::sum);
    }
    return counts;
  }
}
