package org.unlaxer.tinyexpression.loader;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

import org.junit.Test;
import org.unlaxer.compiler.CompileError;
import org.unlaxer.tinyexpression.CalculationContext;
import org.unlaxer.tinyexpression.loader.model.FormulaInfo;
import org.unlaxer.tinyexpression.loader.model.FormulaInfoList;
import org.unlaxer.util.Try;

public class FormulaInfoStoredByteCodePolicyTest {

  @Test
  public void ignoresPersistedByteCodeAndRebuildsFromFormulaText() {
    FormulaInfo original = parseSingle("""
        calculatorName:storedByteCodeIsNotTrusted
        resultType:float
        formula:
        1+1
        ---END_OF_PART---
        """);

    String tampered = original.output().replaceFirst(
        "(?m)^byteCode:[0-9A-Fa-f]+$",
        "byteCode:00");
    assertFalse("fixture must replace the persisted class bytes", tampered.equals(original.output()));

    FormulaInfo restored = parseSingle(tampered);

    assertEquals(2.0f, restored.calculator().calculate(CalculationContext.newContext()));
    assertFalse("restored output must contain freshly generated bytecode",
        restored.output().contains("byteCode:00\n"));
  }

  @Test
  public void rejectsLegacyByteCodeOnlyDocumentByDefault() {
    String byteCodeOnly = """
        calculatorName:legacyByteCodeOnly
        resultType:float
        hash:00000000000000000000000000000000
        hashByByteCode:00000000000000000000000000000000
        byteCode:00
        ---END_OF_PART---
        """;

    Try<FormulaInfoList> parsed = FormulaInfoList.parse(
        byteCodeOnly,
        additionalFields(),
        Thread.currentThread().getContextClassLoader());

    assertTrue(parsed.throwable.orElseThrow() instanceof CompileError);
    assertTrue(parsed.throwable.orElseThrow().getMessage().contains("must contain formula text"));
  }

  private FormulaInfo parseSingle(String text) {
    return FormulaInfoList.parse(
        text,
        additionalFields(),
        Thread.currentThread().getContextClassLoader()).get().get().get(0);
  }

  private FormulaInfoAdditionalFields additionalFields() {
    return new FormulaInfoAdditionalFields("siteId", formulaInfo -> formulaInfo.calculatorName);
  }
}
