package org.unlaxer.tinyexpression.evaluator.javacode;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertThrows;

import java.util.List;
import java.util.concurrent.atomic.AtomicInteger;

import org.junit.After;
import org.junit.Test;
import org.unlaxer.tinyexpression.CalculationContext;
import org.unlaxer.tinyexpression.Calculator;
import org.unlaxer.tinyexpression.Source;
import org.unlaxer.tinyexpression.loader.model.CalculatorCreator;
import org.unlaxer.tinyexpression.loader.model.CalculatorCreatorRegistry;
import org.unlaxer.tinyexpression.parser.ExpressionTypes;

/**
 * A string literal must never leave its Java string literal in the source generated by the
 * javacode backends: a {@code "} inside a single-quoted literal used to close it and the rest of
 * the formula ran as Java code.
 */
public class StringLiteralInjectionTest {

  private static final String PROPERTY = "tinyexpression.injection.test";
  private static final AtomicInteger SEQUENCE = new AtomicInteger();

  private static final SpecifiedExpressionTypes STRING =
      new SpecifiedExpressionTypes(ExpressionTypes.string, ExpressionTypes.string);
  private static final SpecifiedExpressionTypes NUMBER =
      new SpecifiedExpressionTypes(ExpressionTypes._float, ExpressionTypes._float);

  private static final List<CalculatorCreator> JAVA_CODE_CREATORS = List.of(
      CalculatorCreatorRegistry.javaCodeCreator(),
      CalculatorCreatorRegistry.legacyAstCreatorJavaCodeCreator());

  private static final String SET = "System.setProperty(\"" + PROPERTY + "\",\"x\")";

  @After
  public void clearProperty() {
    System.clearProperty(PROPERTY);
  }

  @Test
  public void doubleQuoteInSingleQuotedLiteralIsData() {
    String payload = "A\" + String.valueOf(" + SET + ") + \"B";
    assertNumber("if('hello'.contains('" + payload + "')){1}else{0}", 0f);
    assertNumber("if('x" + payload + "'.contains('" + SET + "')){1}else{0}", 1f);
    assertNumber("if('x'.in('A\" + " + SET + " + \"B','y')){1}else{0}", 0f);
    assertNumber("if('hello'.startsWith('A\" + " + SET + " + \"B')){1}else{0}", 0f);
    assertNumber("if('A\" + " + SET + " + \"B'=='x'){1}else{0}", 0f);
    assertString("'A\" + " + SET + " + \"B' + 'c'", "A\" + " + SET + " + \"Bc");
  }

  @Test
  public void unicodeEscapedQuoteIsData() {
    assertString("'x\\u0022 + " + SET + " + \\u0022'", "x\" + " + SET + " + \"");
  }

  @Test
  public void backslashBeforeQuoteIsData() {
    assertString("'a\\\\\" + " + SET + " + \"'", "a\\\" + " + SET + " + \"");
  }

  @Test
  public void commentAndLineTerminatorsAreData() {
    assertString("'*/ " + SET + "; /*'", "*/ " + SET + "; /*");
    assertString("'// " + SET + "'", "// " + SET);
    assertString("'l1\nl2'", "l1\nl2");
    assertString("' " + "é😀'", " é😀");
  }

  @Test
  public void javaEscapeSequencesKeepTheirMeaning() {
    assertString("'a\\nb'", "a\nb");
    assertString("'it\\'s'", "it's");
    assertString("\"say \\\"hi\\\"\"", "say \"hi\"");
    assertString("'back\\\\slash'", "back\\slash");
    assertString("'\\u0041\\101'", "AA");
  }

  @Test
  public void invalidEscapeIsRejected() {
    for (CalculatorCreator creator : JAVA_CODE_CREATORS) {
      assertThrows(RuntimeException.class, () -> create(creator, "'bad\\q'", STRING));
    }
  }

  private void assertString(String formula, String expected) {
    for (CalculatorCreator creator : JAVA_CODE_CREATORS) {
      Object result = create(creator, formula, STRING).apply(CalculationContext.newConcurrentContext());
      assertEquals(formula, expected, result);
      assertNull(formula, System.getProperty(PROPERTY));
    }
  }

  private void assertNumber(String formula, float expected) {
    for (CalculatorCreator creator : JAVA_CODE_CREATORS) {
      Object result = create(creator, formula, NUMBER).apply(CalculationContext.newConcurrentContext());
      assertEquals(formula, expected, ((Number) result).floatValue(), 0f);
      assertNull(formula, System.getProperty(PROPERTY));
    }
  }

  private static Calculator create(CalculatorCreator creator, String formula,
      SpecifiedExpressionTypes types) {
    return creator.create(new Source(formula), "StringLiteralInjection_" + SEQUENCE.incrementAndGet(),
        types, Thread.currentThread().getContextClassLoader());
  }
}
